-- ============================================================================
-- rpgbot database schema
-- ============================================================================
-- Canonical definition of the Postgres schema the bot and web dashboard expect.
-- Generated from the live database (Postgres 17) and kept in the repo so the
-- database can be rebuilt from scratch.
--
--   Fresh setup:  psql "$DATABASE_URL" -f rpgbot/db/schema.sql
--
-- Snowflake IDs (discord_user_id, discord_guild_id) are stored as BIGINT, not
-- text -- pg returns them as JS strings, which is what the DbUser / DbGuild
-- types expect. Anything queried with `= $1` from JS therefore takes a string.
--
-- Money and XP are BIGINT and come back as strings; the bot does arithmetic on
-- them with BigInt(). Do not "simplify" these to INTEGER.
--
-- This file reflects what is deployed today. Changes go in db/migrations/ as
-- numbered files rather than being edited into an already-deployed table.
--
-- One cosmetic difference from the live database: identity columns are written
-- as GENERATED BY DEFAULT AS IDENTITY here, where the deployed tables use the
-- older serial/nextval form. These behave identically; a database built from
-- this file is equivalent.
-- ============================================================================

BEGIN;

-- ─── Types ───────────────────────────────────────────────────────────────────

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'trade_status') THEN
        -- NB: 'canceled', one L. TradeStatus in types/trading.ts must match.
        CREATE TYPE public.trade_status AS ENUM (
            'pending',
            'accepted',
            'denied',
            'canceled',
            'expired'
        );
    END IF;
END
$$;

-- ─── users ───────────────────────────────────────────────────────────────────
-- One row per Discord user, global across all guilds.

CREATE TABLE IF NOT EXISTS public.users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_user_id BIGINT      NOT NULL UNIQUE,
    username        TEXT,
    avatar_url      TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── guilds ──────────────────────────────────────────────────────────────────
-- One row per server. `config` holds the entire GuildConfig tree (xp, levels,
-- shop, quests, combat, trading, achievements, logging, style) as JSONB, merged
-- against DEFAULT_GUILD_CONFIG by mergeConfig() on read. New config keys need
-- no migration -- that is the point of the JSONB blob.

CREATE TABLE IF NOT EXISTS public.guilds (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_guild_id BIGINT      NOT NULL UNIQUE,
    name             TEXT,
    icon_url         TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    config           JSONB       DEFAULT '{}'::jsonb
);

-- ─── user_guild_profiles ─────────────────────────────────────────────────────
-- Per-user, per-guild progression. This is the hot table: the bot buffers
-- writes to it in an in-memory cache and flushes dirty rows every 30s
-- (see cache/profileService.ts).

CREATE TABLE IF NOT EXISTS public.user_guild_profiles (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT      NOT NULL REFERENCES public.users(id)  ON DELETE CASCADE,
    guild_id        BIGINT      NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,

    xp              BIGINT      NOT NULL DEFAULT 0,
    level           INTEGER     NOT NULL DEFAULT 1,
    gold            BIGINT      NOT NULL DEFAULT 0,
    streak_count    INTEGER     NOT NULL DEFAULT 0,

    last_daily_at   TIMESTAMPTZ,
    last_message_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    inventory       JSONB       DEFAULT '{}'::jsonb,  -- Record<itemId, item>
    temp_roles      JSONB,                            -- Record<roleId, TempRoleState>
    user_stats      JSONB,                            -- UserStats (incl. currentHp)
    achievements    JSONB,                            -- Record<achId, {unlockedAt, progress?}>
    quests          JSONB,                            -- Record<questId, UserQuestState>
    equips          JSONB,                            -- Record<EquipSlot, itemId>
    settings        JSONB,                            -- privacy / DM preferences

    UNIQUE (user_id, guild_id)
);

-- ─── trades ──────────────────────────────────────────────────────────────────
-- Player-to-player trade offers. Item maps are Record<itemId, quantity>.

CREATE TABLE IF NOT EXISTS public.trades (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id            BIGINT NOT NULL REFERENCES public.guilds(id) ON DELETE CASCADE,
    discord_guild_id    BIGINT NOT NULL,

    asker_profile_id    BIGINT NOT NULL REFERENCES public.user_guild_profiles(id) ON DELETE CASCADE,
    asker_discord_id    BIGINT NOT NULL,
    receiver_profile_id BIGINT NOT NULL REFERENCES public.user_guild_profiles(id) ON DELETE CASCADE,
    receiver_discord_id BIGINT NOT NULL,

    asker_items         JSONB  NOT NULL DEFAULT '{}'::jsonb,
    asker_gold          BIGINT NOT NULL DEFAULT 0,
    receiver_items      JSONB  NOT NULL DEFAULT '{}'::jsonb,
    receiver_gold       BIGINT NOT NULL DEFAULT 0,

    status              public.trade_status NOT NULL DEFAULT 'pending',
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at          TIMESTAMPTZ,

    CONSTRAINT trades_gold_nonnegative CHECK (asker_gold >= 0 AND receiver_gold >= 0),
    CONSTRAINT trades_no_self_trade    CHECK (asker_profile_id <> receiver_profile_id)
);

-- At most one open offer between a given pair in a guild.
CREATE UNIQUE INDEX IF NOT EXISTS trades_one_pending_per_pair
    ON public.trades (guild_id, asker_profile_id, receiver_profile_id)
    WHERE status = 'pending';

-- ─── events ──────────────────────────────────────────────────────────────────
-- Audit log. Written in batches by the log buffer (db/events.ts) every 30s and
-- read back by the dashboard's /logs page.

CREATE TABLE IF NOT EXISTS public.events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id         BIGINT NOT NULL REFERENCES public.guilds(id),
    discord_guild_id BIGINT NOT NULL,
    user_id          BIGINT NOT NULL REFERENCES public.users(id),
    target_user_id   BIGINT          REFERENCES public.users(id),

    category         TEXT   NOT NULL,   -- EventCategory: xp | economy | combat | ...
    event_type       TEXT   NOT NULL,   -- e.g. messageXp, grantDaily, streakReset
    source           TEXT,

    xp_delta         BIGINT,
    gold_delta       BIGINT,
    streak_delta     INTEGER,
    level_delta      INTEGER,

    item_id          TEXT,
    quantity         INTEGER,

    old_level        INTEGER,
    new_level        INTEGER,
    old_streak       INTEGER,
    new_streak       INTEGER,

    metadata         JSONB,
    "timestamp"      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_events_guild_created_at
    ON public.events (guild_id, "timestamp" DESC);
CREATE INDEX IF NOT EXISTS idx_events_user_created_at
    ON public.events (user_id, "timestamp" DESC);
CREATE INDEX IF NOT EXISTS idx_events_category_type
    ON public.events (category, event_type);

COMMIT;
